### PR TITLE
add support for five games

### PR DESCRIPTION
**Pull request by ethangreen-dev**
Blocked by #1300

### CODE REVIEW

**Comment by anttimaki** [comment]
For anyone interested in these changes, please note that as of this writing, the communities for the new games aren't yet available on Thunderstore, so the changes are likely to do you little good. Hopefully this will be remedied later today.

**Comment by anttimaki** [comment]
Update to the above: communities are now available on Thunderstore.

**Comment by mathlover3** [comment]
> Update to the above: communities are now available on Thunderstore.

no they arent?

**Comment by Mangochicken13** [comment]
> > Update to the above: communities are now available on Thunderstore.
> 
> no they arent? at least for the app

That's not what the message means, up on the site and in the latest release of r2mm are two seperate things. Again, patience is key; good things come to those who wait

**Pull request merged**
